// Generated by gencpp from file as_arm_description/CheckCollisionValidResponse.msg
// DO NOT EDIT!


#ifndef AS_ARM_DESCRIPTION_MESSAGE_CHECKCOLLISIONVALIDRESPONSE_H
#define AS_ARM_DESCRIPTION_MESSAGE_CHECKCOLLISIONVALIDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace as_arm_description
{
template <class ContainerAllocator>
struct CheckCollisionValidResponse_
{
  typedef CheckCollisionValidResponse_<ContainerAllocator> Type;

  CheckCollisionValidResponse_()
    : valid(false)  {
    }
  CheckCollisionValidResponse_(const ContainerAllocator& _alloc)
    : valid(false)  {
  (void)_alloc;
    }



   typedef uint8_t _valid_type;
  _valid_type valid;





  typedef boost::shared_ptr< ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CheckCollisionValidResponse_

typedef ::as_arm_description::CheckCollisionValidResponse_<std::allocator<void> > CheckCollisionValidResponse;

typedef boost::shared_ptr< ::as_arm_description::CheckCollisionValidResponse > CheckCollisionValidResponsePtr;
typedef boost::shared_ptr< ::as_arm_description::CheckCollisionValidResponse const> CheckCollisionValidResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator1> & lhs, const ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator2> & rhs)
{
  return lhs.valid == rhs.valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator1> & lhs, const ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace as_arm_description

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a04c5033e7efda95fc3786e8d449c6e7";
  }

  static const char* value(const ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa04c5033e7efda95ULL;
  static const uint64_t static_value2 = 0xfc3786e8d449c6e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "as_arm_description/CheckCollisionValidResponse";
  }

  static const char* value(const ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# valid or not\n"
"bool valid\n"
;
  }

  static const char* value(const ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckCollisionValidResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::as_arm_description::CheckCollisionValidResponse_<ContainerAllocator>& v)
  {
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AS_ARM_DESCRIPTION_MESSAGE_CHECKCOLLISIONVALIDRESPONSE_H
