// Generated by gencpp from file blueprintlab_reachsystem_ros_messages/request_list.msg
// DO NOT EDIT!


#ifndef BLUEPRINTLAB_REACHSYSTEM_ROS_MESSAGES_MESSAGE_REQUEST_LIST_H
#define BLUEPRINTLAB_REACHSYSTEM_ROS_MESSAGES_MESSAGE_REQUEST_LIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace blueprintlab_reachsystem_ros_messages
{
template <class ContainerAllocator>
struct request_list_
{
  typedef request_list_<ContainerAllocator> Type;

  request_list_()
    : stamp()
    , device_id(0)
    , requests()  {
    }
  request_list_(const ContainerAllocator& _alloc)
    : stamp()
    , device_id(0)
    , requests(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef uint8_t _device_id_type;
  _device_id_type device_id;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _requests_type;
  _requests_type requests;





  typedef boost::shared_ptr< ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator> const> ConstPtr;

}; // struct request_list_

typedef ::blueprintlab_reachsystem_ros_messages::request_list_<std::allocator<void> > request_list;

typedef boost::shared_ptr< ::blueprintlab_reachsystem_ros_messages::request_list > request_listPtr;
typedef boost::shared_ptr< ::blueprintlab_reachsystem_ros_messages::request_list const> request_listConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator1> & lhs, const ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.device_id == rhs.device_id &&
    lhs.requests == rhs.requests;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator1> & lhs, const ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace blueprintlab_reachsystem_ros_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef8741fe5bbee719df0c3943df9fc5c1";
  }

  static const char* value(const ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef8741fe5bbee719ULL;
  static const uint64_t static_value2 = 0xdf0c3943df9fc5c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "blueprintlab_reachsystem_ros_messages/request_list";
  }

  static const char* value(const ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"uint8 device_id\n"
"int32[] requests\n"
;
  }

  static const char* value(const ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.device_id);
      stream.next(m.requests);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct request_list_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::blueprintlab_reachsystem_ros_messages::request_list_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "device_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.device_id);
    s << indent << "requests[]" << std::endl;
    for (size_t i = 0; i < v.requests.size(); ++i)
    {
      s << indent << "  requests[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.requests[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLUEPRINTLAB_REACHSYSTEM_ROS_MESSAGES_MESSAGE_REQUEST_LIST_H
